#!/usr/bin/env bash
# ============================================================
# Production Setup Script
# Generates .env with secure random secrets from .env.example
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"
ENV_EXAMPLE="$PROJECT_ROOT/.env.example"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   Pizza Box System — Production Setup            ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════╝${NC}"
echo

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
  echo -e "${YELLOW}⚠  .env already exists at:${NC} $ENV_FILE"
  read -p "   Overwrite? (y/N): " confirm
  if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
    echo -e "${RED}✗  Aborted.${NC}"
    exit 0
  fi
  echo
fi

# Verify .env.example exists
if [ ! -f "$ENV_EXAMPLE" ]; then
  echo -e "${RED}✗  .env.example not found at:${NC} $ENV_EXAMPLE"
  exit 1
fi

# ─── Generate secrets ─────────────────────────────────────
echo -e "${GREEN}Generating secure secrets...${NC}"

POSTGRES_PASS=$(openssl rand -base64 32 | tr -d '=/+' | head -c 40)
REDIS_PASS=$(openssl rand -base64 32 | tr -d '=/+' | head -c 40)
JWT_SECRET=$(openssl rand -hex 64)
JWT_REFRESH_SECRET=$(openssl rand -hex 64)

# ─── Prompt for domain ────────────────────────────────────
echo
read -p "Enter your domain (e.g. app.pizzaboxco.com): " DOMAIN
DOMAIN=${DOMAIN:-localhost}

if [ "$DOMAIN" = "localhost" ]; then
  CLIENT_URL="http://localhost"
  VITE_API_URL="http://localhost/api"
else
  CLIENT_URL="https://$DOMAIN"
  VITE_API_URL="https://$DOMAIN/api"
fi

# ─── Prompt for optional services ─────────────────────────
echo
read -p "Anthropic API key (leave empty to skip AI features): " ANTHROPIC_KEY
ANTHROPIC_KEY=${ANTHROPIC_KEY:-}

echo
echo -e "${CYAN}Email settings (leave empty to skip):${NC}"
read -p "  SMTP host [smtp.gmail.com]: " SMTP_HOST
SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
read -p "  SMTP port [587]: " SMTP_PORT
SMTP_PORT=${SMTP_PORT:-587}
read -p "  SMTP user: " SMTP_USER
SMTP_USER=${SMTP_USER:-}
read -p "  SMTP password: " SMTP_PASS
SMTP_PASS=${SMTP_PASS:-}
read -p "  From email [noreply@$DOMAIN]: " EMAIL_FROM
EMAIL_FROM=${EMAIL_FROM:-noreply@$DOMAIN}

# ─── Write .env ───────────────────────────────────────────
cat > "$ENV_FILE" << EOF
# ============================================================
# PIZZA BOX SYSTEM — PRODUCTION ENVIRONMENT
# Generated by setup-prod.sh on $(date -Iseconds)
# ============================================================

# ------ Database ------
POSTGRES_PASSWORD=$POSTGRES_PASS
DATABASE_URL=postgresql://postgres:${POSTGRES_PASS}@postgres:5432/pizzabox

# ------ Redis ------
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=$REDIS_PASS

# ------ JWT ------
JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET

# ------ Server ------
PORT=3001
NODE_ENV=production
LOG_LEVEL=info

# ------ CORS ------
CLIENT_URL=$CLIENT_URL

# ------ Invoice ------
INVOICE_PREFIX=INV

# ------ AI (Anthropic) ------
ANTHROPIC_API_KEY=$ANTHROPIC_KEY

# ------ Email ------
SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT
SMTP_SECURE=false
SMTP_USER=$SMTP_USER
SMTP_PASS=$SMTP_PASS
EMAIL_FROM=$EMAIL_FROM

# ------ Frontend (Vite) ------
VITE_API_URL=$VITE_API_URL
VITE_APP_NAME=Pizza Box Manager
EOF

chmod 600 "$ENV_FILE"

echo
echo -e "${GREEN}✓  .env created at:${NC} $ENV_FILE"
echo -e "${GREEN}✓  File permissions set to 600 (owner read/write only)${NC}"
echo
echo -e "${CYAN}Generated credentials:${NC}"
echo -e "  Postgres password: ${YELLOW}${POSTGRES_PASS}${NC}"
echo -e "  Redis password:    ${YELLOW}${REDIS_PASS}${NC}"
echo -e "  JWT secrets:       ${YELLOW}(128-char hex — see .env)${NC}"
echo
echo -e "${CYAN}Next steps:${NC}"
echo -e "  1. Run ${YELLOW}./scripts/setup-ssl.sh${NC} to configure SSL certificates"
echo -e "  2. Run ${YELLOW}docker compose -f docker-compose.prod.yml up --build -d${NC}"
echo -e "  3. Save these credentials in a secure password manager"
echo
